name: Need Help
description: Feel free to ask for help.
title: Need help report
labels: ["need-help 👀"]
body:
  - type: textarea
    id: need_help_description
    attributes:
      label: Describe the issue you are facing
      description: A clear and concise description of what the issue is
    validations:
      required: true
  - type: textarea
    id: issue_reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior. If can't be reproduced then leave blank
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: need_help_expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: need_help_screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
  - type: textarea
    id: need_help_desktop
    attributes:
      label: Desktop (please complete the following information)
      placeholder: |
        - OS: [e.g. iOS]
        - Browser: [e.g. chrome, safari]
        - Version: [e.g. 22]
  - type: textarea
    id: need_help_smartphone
    attributes:
      label: Smartphone (please complete the following information)
      placeholder: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser: [e.g. stock browser, safari]
        - Version: [e.g. 22]
  - type: textarea
    id: need_help_additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
